### ISSUE TITLE
catkin tools does not produce devel/includes

### ISSUE THREAD

**Issue by abishekh** [CogRob/catkin_grpc#25]
Seems like building with catkin_make works as intended. Then I tried to build it with [catkin tools](https://catkin-tools.readthedocs.io/en/latest/index.html) and it only generates the build files and not the devel/includes.

**Comment by BillWSY** [comment]
That’s strange. We always used `catkin build` to build our software. Can you provide a minimal example that produces this issue? Also can you report your `catkin-tools` version, ROS version, OS version, grpc version? Did you compile grpc from source or do you use a ros Debian package?

**Comment by BillWSY** [comment]
Also, can you check if `catkin_ws/devel/.private/package_name/include/` is correctly generated? Can you collect output from `catkin build --verbose` and post it here?

**Comment by abishekh** [comment]
Can't post console output because its a work-system. However I can confirm the `catkin_ws/devel/.private/...` is being generated.

**Comment by BillWSY** [comment]
`catkin-tools` is responsible to create symlinks form `.private` directory to `devel/...`. Can you try upgrading your `catkin-tools` to the latest?

Reference: http://catkin-tools.readthedocs.io/en/latest/advanced/linked_develspace.html
