### ISSUE TITLE
Running into build warnings and errors with 0.0.6

### ISSUE THREAD

**Issue by abishekh** [CogRob/catkin_grpc#26]
I seem to be running into some warnings on my own system and some errors within Docker containers when I try to build it there. 

Host system:
![screenshot from 2018-02-14 06-40-08](https://user-images.githubusercontent.com/489699/36204742-1660ab36-1152-11e8-9b99-f4acb5f5ddad.png)

Docker image:
![screenshot from 2018-02-14 06-28-21](https://user-images.githubusercontent.com/489699/36204770-272425d8-1152-11e8-8e50-5d480609fed7.png)

**Comment by BillWSY** [comment]
The warnings seemed rooted in grpc source code. Maybe you can open an issue with grpc developers. However this should not be a big issue if you are just using grpc. The alternative is to disable all the warnings through some flags, which I don't feel necessary.

The error seems to be in downloading a file from github. Is you network stable? Can you try building the image on another machine?

**Comment by BillWSY** [comment]
I am closing this issue now for the lack of response. Please feel free to open another issue if current grpc is not building.
