### ISSUE TITLE
Compiler warnings on gcc 7 

### ISSUE THREAD

**Issue by abishekh** [CogRob/catkin_grpc#28]
Hi,
I noticed some issues when building with gcc-7 under 18.04 LTS . zlib tends to not build because gcc-7 is treating warnings as errors by default - gcc-5.4 works fine. The proper fix probably lies inside the configure script for zlib but I was wondering if there was some way to turn off warnings within the cmake script on this repo for the time being ?

**Comment by BillWSY** [comment]
This line:
https://github.com/CogRob/catkin_grpc/blob/5040f4d261edf2f4f3f1fbb3537d914ebead0ca5/grpc/CMakeLists.txt#L105
starts the building process. Maybe you can use it as a starting point and dig to the command that builds zlib and pass a flag to disable the warning.

**Comment by abishekh** [comment]
This can be resolved by simply updating the hashes for the submodules in the build script. I guess I had slipped into an older version of zlib. My bad.
