### ISSUE TITLE
ROS Melodic support?

### ISSUE THREAD

**Issue by bochen87** [CogRob/catkin_grpc#32]
Hi,

Are you planning on releasing a version for ros melodic?

**Comment by BillWSY** [comment]
Eventually, yes. I will do it when I have some time.

But it will not happen today, and even if I release it today, it will take month before it is available in the apt repo. So I would suggest you compile-install the package for now.

**Comment by BillWSY** [comment]
https://github.com/ros/rosdistro/pull/18271
Will see how it goes.

**Comment by bochen87** [comment]
thanks a lot!!

**Comment by BillWSY** [comment]
Current build failure: http://build.ros.org/job/Mdev__grpc__ubuntu_bionic_amd64/1/display/redirect
Related: https://github.com/ros/rosdistro/issues/18272

**Comment by BillWSY** [comment]
Related: https://github.com/ros/rosdistro/pull/18340#event-1712764512

**Comment by BillWSY** [comment]
Compiled in melodic, just need to wait for public sync

http://build.ros.org/job/Mbin_uB64__grpc__ubuntu_bionic_amd64__binary/8/display/redirect
