### ISSUE TITLE
my grpc project build error

### ISSUE THREAD

**Issue by lifekill1978** [CogRob/catkin_grpc#34]
... ...
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'grpc'
-- ==> add_subdirectory(ginger_admin/grpc)
-- +++ processing catkin package: 'cm_ginger'
-- ==> add_subdirectory(ginger_admin/cm_ginger)
-- Found protoc at: PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND
-- Found grpc_cpp_plugin at: GRPC_CPP_PLUGIN-NOTFOUND
-- Found grpc_python_plugin at: GRPC_PYTHON_PLUGIN-NOTFOUND
-- Found protobuf libraries: LIBPROTOBUF-NOTFOUND;LIBZ-NOTFOUND
-- Found grpc libraries: LIBARES-NOTFOUND;LIBBORINGSSL-NOTFOUND;LIBGPR-NOTFOUND;LIBGRPC-NOTFOUND;LIBGRPCPP-NOTFOUND;LIBGRPC_CRONET-NOTFOUND;LIBGRPCPP_CRONET-NOTFOUND;LIBGRPCPP_CORE_STATS-NOTFOUND;LIBGRPCPP_ERROR_DETAILS-NOTFOUND;LIBGRPC_PLUGIN_SUPPORT-NOTFOUND;LIBGRPCPP_REFLECTION-NOTFOUND;LIBGRPC_UNSECURE-NOTFOUND;LIBGRPCPP_UNSECURE-NOTFOUND
-- Found protobuf libraries: LIBPROTOBUF-NOTFOUND;LIBZ-NOTFOUND
-- Found grpc libraries: LIBARES-NOTFOUND;LIBBORINGSSL-NOTFOUND;LIBGPR-NOTFOUND;LIBGRPC-NOTFOUND;LIBGRPCPP-NOTFOUND;LIBGRPC_CRONET-NOTFOUND;LIBGRPCPP_CRONET-NOTFOUND;LIBGRPCPP_CORE_STATS-NOTFOUND;LIBGRPCPP_ERROR_DETAILS-NOTFOUND;LIBGRPC_PLUGIN_SUPPORT-NOTFOUND;LIBGRPCPP_REFLECTION-NOTFOUND;LIBGRPC_UNSECURE-NOTFOUND;LIBGRPCPP_UNSECURE-NOTFOUND
... ...
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBARES
    linked by target "cm_ginger_proto" in directory /home/ros/lison_ws/src/ginger_admin/cm_ginger
LIBBORINGSSL
    linked by target "cm_ginger_proto" in directory /home/ros/lison_ws/src/ginger_admin/cm_ginger
LIBGPR
    linked by target "cm_ginger_proto" in directory /home/ros/lison_ws/src/ginger_admin/cm_ginger
... ...

**Comment by lifekill1978** [comment]
If first build(catkin_make) grpc success, then build my project, it's OK.
But if grpc and my project are building together, I met above build error.
Thanks a lots.

**Comment by BillWSY** [comment]
You will need to let catkin know that your package depends on grpc. https://github.com/CogRob/catkin_grpc_examples/blob/470e29b5556e4f5ef584b8fb38984204c577a095/greeter/package.xml#L11

**Comment by lifekill1978** [comment]
I git clone catkin_grpc_examples/greeter, but met same build error if together build with grpc, build log in attachment.
Build tool is using catkin_make.
Thanks a lots.
[catkin_example_build-error.txt](https://github.com/CogRob/catkin_grpc/files/3444793/catkin_example_build-error.txt)
[CMakeError.log](https://github.com/CogRob/catkin_grpc/files/3444796/CMakeError.log)
[CMakeOutput.log](https://github.com/CogRob/catkin_grpc/files/3444797/CMakeOutput.log)

**Comment by BillWSY** [comment]
At this point, I would recommend you try `catkin-tools` as the build tool.

https://catkin-tools.readthedocs.io/en/latest/

**Comment by BillWSY** [comment]
In addition, you can always install ros-kinetic-grpc instead of building this on your own.

**Comment by lifekill1978** [comment]
First install ros-kinetic-grpc, build catkin_grpc_examples/greeter is OK. I will try catkin-tools .
Thank you very much.
