### ISSUE TITLE
Noetic release

### ISSUE THREAD

**Issue by furushchev** [CogRob/catkin_grpc#40]
I use the nice packages in this repository on melodic and want to use them also in noetic.
Is there any plan to release the packages in this repository to noetic distro?

**Comment by furushchev** [comment]
Currently, the build of the repository ends with error on ubuntu 20.04 / noetic distro:

```
Errors     << grpc:make /catkin_ws/logs/grpc/build.make.000.log                
In file included from /usr/include/string.h:495,                                   
                 from third_party/cares/cares/setup_once.h:35,                   
                 from third_party/cares/cares/ares_setup.h:214,                          
                 from third_party/cares/cares/ares_parse_ptr_reply.c:17:
In function ‘strncpy’,                                                                                                                                                                          inlined from ‘ares_parse_ptr_reply’ at third_party/cares/cares/ares_parse_ptr_reply.c:134:11:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: error: ‘__builtin_strncpy’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));                           
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
third_party/cares/cares/ares_parse_ptr_reply.c: In function ‘ares_parse_ptr_reply’:
third_party/cares/cares/ares_parse_ptr_reply.c:134:47: note: length computed here                               
  134 |           strncpy(aliases[aliascnt], rr_data, strlen(rr_data)+1);                                                                                                                  
      |                                               ^~~~~~~~~~~~~~~    
third_party/cares/cares/ares_parse_ptr_reply.c: At top level:     
cc1: error: unrecognized command line option ‘-Wno-invalid-source-encoding’ [-Werror]
cc1: all warnings being treated as errors                       
make[3]: *** [Makefile:2898: /catkin_ws/build/grpc/grpc_build/objs/opt/third_party/cares/cares/ares_parse_ptr_reply.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/build_grpc.dir/build.make:115: grpc/src/build_grpc-stamp/build_grpc-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:554: CMakeFiles/build_grpc.dir/all] Error 2
make: *** [Makefile:141: all] Error 2                                                   
```

**Comment by furushchev** [comment]
From grpc v1.25.0 upto v1.34.1, I confirmed on my laptop that it works with the package on both melodic and noetic.
I sent a PR to bump the version to v1.34.1.
https://github.com/CogRob/catkin_grpc/pull/42

**Comment by BillWSY** [comment]
Thank you for the contribution!

**Comment by garaemon** [comment]
@BillWSY Do you have any plan to release this package to noetic?

**Comment by furushchev** [comment]
@BillWSY Kindly ping to maintainer :smile:  (Any update on this issue?)

**Comment by garaemon** [comment]
@BillWSY Kindly pinging. 
I'm very looking forward to installing catkin_grpc via apt package on noetic environment.

**Comment by BillWSY** [comment]
https://github.com/ros/rosdistro/pull/31483

Thanks for the suggestions. Hope this will work.

**Comment by garaemon** [comment]
@BillWSY Thank you very much!

**Comment by BillWSY** [comment]
It seems the build fails in ROS buildfarm.

https://build.ros.org/job/Nbin_uF64__grpc__ubuntu_focal_amd64__binary/
https://build.ros.org/job/Nbin_ufv8_uFv8__grpc__ubuntu_focal_arm64__binary/

I was trying to reproduce the error locally but on Ubuntu 20.04 it does not fail. I also tried to reproduce with http://prerelease.ros.org but it failed due to [this bug](https://answers.ros.org/question/347063/error-pre-release-melodic/), the proposed fix didn't work for me. If anyone is interested in taking a look it would be great.

**Comment by garaemon** [comment]
@BillWSY 

Finally, I reproduced the error by the following command:
```
generate_prerelease_script.py   https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml   noetic default ubuntu focal amd64   --custom-repo  grpc:git:https://github.com/CogRobRelease/
catkin_grpc-release.git:release/noetic/grpc/0.0.10-2   --level 1   --output-dir ./
```

I think you need to release the latest version which includes @furushchev 's patch #42 and #43.

The [0.0.10](https://github.com/CogRob/catkin_grpc/releases/tag/0.0.10) was released in 2018 and the version uses old grpc.

**Comment by garaemon** [comment]
@BillWSY A friendly reminder

**Comment by garaemon** [comment]
I've released the new version of catkin_grpc as 0.0.11 and the build passes in ROS buildfarm!

https://build.ros.org/job/Nbin_uF64__grpc__ubuntu_focal_amd64__binary/157/console

**Comment by soldierofhell** [comment]
apt install ros-noetic-grpc still doesn't work for me

**Comment by garaemon** [comment]
catkin_grpc 0.0.11 was released after the latest noetic release on May 18th, 2022. 
* https://github.com/ros/rosdistro/tags
* https://discourse.ros.org/c/release/noetic/66

Please wait for the next sync.

**Comment by furushchev** [comment]
It was already released and works well. Thank you all for your support!
