### ISSUE TITLE
Error when using generate_proto

### ISSUE THREAD

**Issue by fouad1995** [CogRob/catkin_grpc#46]
When using GRPC flag in generate proto function I faced cmake error:
`CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBGRPCPP_CRONET
`
And after some debugging I found that generate_proto.cmake can't find LIBGRPC_CRONET grpc_cronet library which force the flag not to set.

And this is from console log.
`LIBGRPC_CRONET-NOTFOUND;LIBGRPCPP_CRONET-NOTFOUND`

Thanks in advance.

**Comment by rockenbf** [comment]
I had the same issue and removing the library search should to the trick. (#47)

**Comment by ShiauweiZhao** [comment]
> I had the same issue and removing the library search should to the trick. (#47)

you are right, thx

**Comment by BillWSY** [comment]
Seems to be fixed by #47
