### ISSUE TITLE
在ubuntu20.04中用命令安装（sudo apt install ros-noetic-grpc），出现编译ros节点错误的现象

### ISSUE THREAD

**Issue by tiger7chan** [CogRob/catkin_grpc#48]
`
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Found protoc at: /opt/ros/noetic/lib/grpc/protobuf/protoc
-- Found grpc_cpp_plugin at: /opt/ros/noetic/lib/grpc/grpc_cpp_plugin
-- Found grpc_python_plugin at: /opt/ros/noetic/lib/grpc/grpc_python_plugin
-- Found protobuf libraries: /opt/ros/noetic/lib/protobuf/libprotobuf.a;/opt/ros/noetic/lib/libz.a
-- Found grpc libraries: /opt/ros/noetic/lib/libaddress_sorting.so;/opt/ros/noetic/lib/libares.a;/opt/ros/noetic/lib/libboringssl.a;/opt/ros/noetic/lib/libgpr.so;/opt/ros/noetic/lib/libgrpc.so;/opt/ros/noetic/lib/libgrpc++.so;/opt/ros/noetic/lib/libgrpc_abseil.a;/opt/ros/noetic/lib/libgrpc++_alts.so;LIBGRPC_CRONET-NOTFOUND;LIBGRPCPP_CRONET-NOTFOUND;/opt/ros/noetic/lib/libgrpc++_error_details.so;/opt/ros/noetic/lib/libgrpcpp_channelz.so;/opt/ros/noetic/lib/libgrpc_plugin_support.a;/opt/ros/noetic/lib/libgrpc++_reflection.so;/opt/ros/noetic/lib/libgrpc_unsecure.so;/opt/ros/noetic/lib/libgrpc++_unsecure.so
-- arm_srv_ros: 1 messages, 2 services
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBGRPCPP_CRONET
    linked by target "arm_grpc" in directory /home/lpt/ros_wp/src/arm_srv_ros
LIBGRPC_CRONET
    linked by target "arm_grpc" in directory /home/lpt/ros_wp/src/arm_srv_ros

-- Configuring incomplete, errors occurred!
See also "/home/lpt/ros_wp/build/CMakeFiles/CMakeOutput.log".
See also "/home/lpt/ros_wp/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed
`

![5CEWB~_CG7B$HL%O7 MMD$S](https://github.com/CogRob/catkin_grpc/assets/16042289/057588dd-0b15-4b40-b9c1-d3c0d464a042)
发现上面多包含了2个grpc的库，去掉后才能正常编译，在仓库里面没看到有引用这2个库

**Comment by BillWSY** [comment]
It looks like this was fixed by #47. Thanks! Please feel free to reopen if it is still outstanding.
