### ISSUE TITLE
git-branch model does not work with ros tools

### ISSUE THREAD

**Issue by BillWSY** [CogRob/catkin_grpc#6]
We are trying to prevent direct push to master branch and force squash-merge. However, ROS tools ("catkin_prepare_release") only works with a direct push to master (it automatically commits package.xml and creates a tag).

For now I am dropping review requirements for master branch, but force push is still prevented.

Just remember not to push to master directly with massive small changes, unless you are doing a release.

**Comment by tfoote** [comment]
@BillWSY you can stop catkin_prepare_release and push manually via a branch to make a PR and tag it manually after merging. catkin_prepare_release is just a helper tool to save manual work.

**Comment by BillWSY** [comment]
Thanks for the information. Now I understand how these tools work. Really appreciate it :)
