### ISSUE TITLE
Package fails to build on debian stretch

### ISSUE THREAD

**Issue by mikaelarguedas** [CogRob/catkin_grpc#7]
@BillWSY  [This job](http://build.ros.org/view/Lbin_dsv8_dSv8/job/Lbin_dsv8_dSv8__grpc__debian_stretch_arm64__binary/) failed to build consistently since this package was released. It looks like `git clone` crashes in qemu due to the massive amount of data to download.

Is there anything we can do to reduce the amount of data cloned during the build process?
`git clone` is known to hang in qemu but that's the first time I see it crash hard consistently and am not sure there is much we can do on our side to solve it. I tried to reproduce it locally in a container but never succeeded to go that far in the build process because the cloning of the third party repos hangs forever

**Comment by BillWSY** [comment]
Let me see if we could use HTTP download instead of git clone.

Could there be a network connection problem? I never had any problem cloning these git repos.

**Comment by mikaelarguedas** [comment]
I think it happens only in hybrid environment, I didn't have any issue cloning them on amd64 machines, this seems to happen only within qemu. The build folder ends up being 1.5GB so I'm not surprised that it fails sometimes on slow IO access environment like qemu

**Comment by BillWSY** [comment]
Let's see if 0.0.3 (https://github.com/ros/rosdistro/pull/16000) will fix the problem.

**Comment by BillWSY** [comment]
The latest build succeed: http://build.ros.org/job/Lbin_dsv8_dSv8__grpc__debian_stretch_arm64__binary/35/display/redirect
